# ======================= #
#        OH-MY-ZSH        #
# ======================= #


# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# Commented as I apply starship below
# ZSH_THEME="spaceship"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  aws
  colored-man-pages
  copyfile
  copypath
  docker
  docker-compose
  dotenv
  fzf
  git
  globalias
  helm
  istioctl
  jsontools
  kubectl
  pip
  poetry
  python
  sudo
  terraform
  vault
  virtualenv
  vscode
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"


# ======================= #
#        MY-CONFIG        #
# ======================= #


# ------ #
# PYTHON #
# ------ #

# Deferred: `conda shell.zsh hook` starts a Python interpreter (~700ms), so it
# loads on first use instead. Re-running `conda init` will overwrite this.
conda() {
    unset -f conda
    __conda_setup="$("$HOME/miniconda3/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "$__conda_setup"
    elif [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniconda3/bin:$PATH"
    fi
    unset __conda_setup
    conda "$@"
}

# set up pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
# --no-rehash skips regenerating every shim on each shell start. Run
# `pyenv rehash` after installing a version or a package with an entry point.
eval "$(pyenv init - --no-rehash)"

# set up openssl
export PATH="/opt/homebrew/opt/openssl@3/bin:$PATH"

# fix grpcio
export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1

# created by `pipx` on 2024-01-22 12:15:11 with `pipx ensurepath`
export PATH="$PATH:$HOME/.local/bin"

# ------ #
# DOCKER #
# ------ #

# set up podman
PATH=/opt/podman/bin:$PATH

# ------- #
# GENERAL #
# ------- #

# set up starship prompt
eval "$(starship init zsh)"

# set up buildpacks autocompletion
. $(pack completion --shell zsh)

# set up eksctl autocompletion
fpath=($fpath ~/.oh-my-zsh/completions)

# custom aliases
source ~/.aliases

# other
source $HOME/.config/broot/launcher/bash/br
export XDG_CONFIG_HOME=$HOME/.config
export DOCKER_HOST="unix://$HOME/.local/share/containers/podman/machine/podman.sock"

export NVM_DIR="$HOME/.config/nvm"
# --no-use skips nvm's startup version resolution. On its own that leaves node
# off PATH, so the default version's bin is added below; `nvm use` still
# switches whenever a project needs another version.
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use  # This loads nvm
if [[ -r "$NVM_DIR/alias/default" ]]; then
    __nvm_default="$(<"$NVM_DIR/alias/default")"
    __nvm_bin=("$NVM_DIR/versions/node/v${__nvm_default#v}"*/bin(N))
    [[ -n "$__nvm_bin" ]] && export PATH="${__nvm_bin[1]}:$PATH"
    unset __nvm_default __nvm_bin
fi
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# set up zoxide (must be initialized last so its shell hooks aren't clobbered)
eval "$(zoxide init zsh)"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Claude Code marks agent-spawned runs with CLAUDE_CODE_CHILD_SESSION, which disables
# transcript saving. A long-lived daemon started from such a shell (e.g. `herdr server`)
# captures the marker and leaks it into every shell it spawns afterwards. An interactive
# shell is never a child session, and this file is not sourced by the non-interactive
# `zsh -c` that Claude Code actually uses for nested runs, so dropping it here is safe.
unset CLAUDE_CODE_CHILD_SESSION
